{
 "title": "Heartbeat Monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Active Alerts",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "heartbeat_db",
     "rawSql": "SELECT COUNT(*) AS active_count\r\nFROM heartbeat_alerts\r\nWHERE resolved_flag = false;"
    }
   ]
  },
  {
   "title": "Total Heartbeats",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "heartbeat_db",
     "rawSql": "SELECT COUNT(*) AS total_heartbeats\r\nFROM heartbeats;"
    }
   ]
  },
  {
   "title": "Anomalies By Type In Invalid Categories",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "heartbeat_db",
     "rawSql": "SELECT anomaly_type AS type, COUNT(*) AS count\r\nFROM heartbeats\r\nWHERE validation_status != 'valid'\r\nGROUP BY anomaly_type;"
    }
   ]
  },
  {
   "title": "Overall Health Of Incoming Heartbeat Data ",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "heartbeat_db",
     "rawSql": "SELECT validation_status AS status, COUNT(*) AS count\r\nFROM heartbeats\r\nGROUP BY validation_status;\r\n"
    }
   ]
  },
  {
   "title": "Alert Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "dataset": "heartbeat_db",
     "rawSql": "SELECT\r\n  DATE_TRUNC('minute', timestamp) AS time,\r\n  COUNT(*) AS alert_count\r\nFROM heartbeat_alerts\r\nWHERE resolved_flag = false\r\nGROUP BY time\r\nORDER BY time;"
    }
   ]
  },
  {
   "title": "Top Ten Patients With Anomaly",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "dataset": "heartbeat_db",
     "rawSql": "SELECT patient_id, COUNT(*) AS anomaly_count\r\nFROM heartbeats\r\nWHERE validation_status != 'valid'\r\nGROUP BY patient_id\r\nORDER BY anomaly_count DESC\r\nLIMIT 10;"
    }
   ]
  },
  {
   "title": "Heartbeat Trends",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "dataset": "heartbeat_db",
     "rawSql": "SELECT\r\n  DATE_TRUNC('minute', timestamp) AS time,\r\n  AVG(heartbeat_value) AS avg_heartbeat,\r\n  MIN(heartbeat_value) AS min_heartbeat,\r\n  MAX(heartbeat_value) AS max_heartbeat\r\nFROM heartbeats\r\nGROUP BY time\r\nORDER BY time;"
    }
   ]
  },
  {
   "title": "Recent Alerts",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "dataset": "heartbeat_db",
     "rawSql": "SELECT \r\n  timestamp,\r\n  patient_id,\r\n  heartbeat_value,\r\n  alert_category,\r\n  resolved_flag\r\nFROM heartbeat_alerts\r\nORDER BY timestamp DESC\r\nLIMIT 50;"
    }
   ]
  }
 ]
}